### ISSUE TITLE
[Legitimate Site Blocked] kyber.network

### ISSUE THREAD

**Issue by viet-nv** [phishfort/phishfort-lists#1136]
https://kyber.network/

**Comment by shrestha-milann** [comment]
The domain has been removed from the blacklist. It will take a few
minutes to reflect. Please let us know if the issue is resolved.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by viet-nv** [comment]
Thanks
